/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/data/levels`; params?: Router.UnknownInputParams; } | { pathname: `/levels`; params?: Router.UnknownInputParams; } | { pathname: `/levels/1`; params?: Router.UnknownInputParams; } | { pathname: `/levels/2`; params?: Router.UnknownInputParams; } | { pathname: `/levels/3`; params?: Router.UnknownInputParams; } | { pathname: `/levels/3/profile`; params?: Router.UnknownInputParams; } | { pathname: `/levels/4`; params?: Router.UnknownInputParams; } | { pathname: `/lib/progress`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/data/levels`; params?: Router.UnknownOutputParams; } | { pathname: `/levels`; params?: Router.UnknownOutputParams; } | { pathname: `/levels/1`; params?: Router.UnknownOutputParams; } | { pathname: `/levels/2`; params?: Router.UnknownOutputParams; } | { pathname: `/levels/3`; params?: Router.UnknownOutputParams; } | { pathname: `/levels/3/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/levels/4`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/progress`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/data/levels${`?${string}` | `#${string}` | ''}` | `/levels${`?${string}` | `#${string}` | ''}` | `/levels/1${`?${string}` | `#${string}` | ''}` | `/levels/2${`?${string}` | `#${string}` | ''}` | `/levels/3${`?${string}` | `#${string}` | ''}` | `/levels/3/profile${`?${string}` | `#${string}` | ''}` | `/levels/4${`?${string}` | `#${string}` | ''}` | `/lib/progress${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/data/levels`; params?: Router.UnknownInputParams; } | { pathname: `/levels`; params?: Router.UnknownInputParams; } | { pathname: `/levels/1`; params?: Router.UnknownInputParams; } | { pathname: `/levels/2`; params?: Router.UnknownInputParams; } | { pathname: `/levels/3`; params?: Router.UnknownInputParams; } | { pathname: `/levels/3/profile`; params?: Router.UnknownInputParams; } | { pathname: `/levels/4`; params?: Router.UnknownInputParams; } | { pathname: `/lib/progress`; params?: Router.UnknownInputParams; };
    }
  }
}
